# -*- coding: utf-8 -*-
"""Assingnment In Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgxJHmSkDhVxm3H38xuGCrbchcifDtkC
"""

##Write a Python program that takes user inputs to calculate the area of a rectangle, square, triangle, and circle.

length =float(input("Enter length of Rectangle: "))
width = float(input("Enter width of Rectangle: "))
area = length * width
print("Area of rectangle:",area)

side = float(input("Enter the side of the square:"))
perimeter = 4 * side
print("Perimeter of square:",perimeter)

base =float(input("Base of Triangle:"))
height =float(input("Height of Triangle:"))
Area = 0.5 * base * height
print("Area of th Triangle:",Area)

radius = float(input("Enter the Radius of Circle:"))
circumference = 2*3.14*radius
print("Circumference of circle:",circumference)

##write a program to calculate simple interest using the formula (SI = P × R × T / 100).

P=float(input("Enter the principal amount:"))
R=float(input("Enter the Rate of interest:"))
T=float(input("Enter the Time:"))

SI = (P*R*T)/100
print("Simple Interest amount:",SI)

##Write a program that takes a purchase amount and calculates the discount (10% for $100–$500, 20% above $500, none below $100) and the final amount.

Amount = float(input("Total Purchase price:"))

if(Amount<100):
    Discount =0
elif(Amount>=100 and Amount<= 500):
    Discount= Amount*0.10
else:
    Discount= Amount*0.20

Final_amount = Amount- Discount

print("n/Bill Details")
print(f"PurchaseAmount: ${Amount}")
print(f"DiscountAmount: ${Discount}")
print(f"FinalpayAmount: ${Final_amount}"

##Write a program where the user enters Red, Yellow, or Green, and the program displays the corresponding action or "Invalid color."

color=input("light color:")
color = color.lower()

if (color=="red"):
    print("Stop")
elif(color=="yellow"):
    print("Ready to move")
elif(color=="green"):
    print("Go")
else:
    print("invalid Color")

##Write a program that accepts a student's marks and displays their grade based on the given grading scale.

marks =int(input("enter the mark:"))

if (marks>=90):
           print("Grade A")

elif (marks >=75 and marks <90):
           print("Grade B")
elif (marks >=50 and marks <75):
    print("Grade C")
else:
    print("Fail")

##Write a program that takes an integer and checks whether it is odd or even and whether it is divisible by 5.

num =int(input("Enter the number:"))

if(num%2==0):
    print(f"{num} is even")
else:
    print(f"{num} is odd")


if (num%5==0):
    print(f"{num} is divisble by 5")
else:
    print(f"{num} is not divisble by 5")

##Write a program that checks password strength as Strong (≥8 characters), Medium (5–7 characters), or Weak (<5 characters).

password = input("Enter your password:")

length = len(password)

if (length>=8):
    print("Strong password")
elif (length>5 and length<7):
    print("Medium")
else:
    print("weak password")

##Write a program that accepts electricity units consumed and calculates the total bill using the slab rates.
units=int(input("Enter units:"))

if(units<=100):
    amount=units*0.5

elif(units>100 and units<200):
    amount=(100*0.5)+(units-100)*0.75

else:
    amount=(100*0.5)+(100*0.75)+(units-200)*1

print("n/-----EB bill----")
print(f"units:{units}")
print(f"amount:{amount}")

##Write a program that determines loan eligibility based on age (21–60) and monthly income (≥$5000).

age =int(input("enter your age:"))
salary=int(input("enter your salary:"))

if(age >=21 and age<=60 and salary>5000):
    print("your eligible")
else:
    print("your not eligible")

##Write a program that takes temperature as input and displays the corresponding weather alert.

Temp=float(input("Enter a Temperature:"))

if(Temp<0):
           print("Freezing weather",Temp)
elif(Temp>=0 and Temp<=20):
           print("Cold weather",Temp)
elif(Temp>20 and Temp<30):
         print("Warm weather",Temp)
else:
    print("Hot weather",Temp)



